services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=db_faceUnah;user=root;password=2003
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: db_faceUnah
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=2003
       - MYSQL_DATABASE=db_faceUnah
    ports:
       - 3307:3306
    volumes:
      - db_faceUnah:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "root", "-p2003"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  db_faceUnah:

